version: "3.9"

services:
  reverse-proxy:
    image: nginx:latest
    container_name: nf4_reverse_proxy
    restart: unless-stopped
    ports:
      - "3001:80"
    volumes:
      # Static config files (bind mount so updates are instant)
      - ./configuration/toml:/var/www/html/configuration/toml:ro
      - ./configuration/bin:/var/www/html/configuration/bin:ro

      # Custom nginx config (see below)
      - ./nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - proposer
      - configuration
    networks:
      - nightfall_network
